### ISSUE TITLE
Does not have valid V10 manifest

### ISSUE THREAD

**Issue by LowerMechancial** [oOve/lasers#16]
Here is the console error output:
```
setup.js:292 Error: Unable to load valid module manifest data from "https://github.com/oOve/lasers/releases/latest/download/module.json"
Module Model Validation Errors
[Module.packs]: Model Validation Errors
The Compendium pack "lasers" of the "Actor" type must declare the "system" upon which it depends.
```

**Comment by StudioNirin** [comment]
Is this module currently functional for v10?

**Comment by oOve** [comment]
Lasers is still not yet ported for v10 no.
I maintain a list of my progress on my modules on my discord channel, but will update this issue when it is good to go.
https://discord.com/channels/798236970992009237/1005493664375644241

**Comment by oOve** [comment]
Release 10.0.1 is now v10 compatible.
