### ISSUE TITLE
I can't make it work...

### ISSUE THREAD

**Issue by brunocalado** [oOve/lasers#6]
Hi! Great job again!

I created a light source and I'm tryting to redirect the light with the mirror. But, I can't make it work...

![image](https://user-images.githubusercontent.com/4999783/161622377-ad4baf5b-fca0-4047-b971-ce9983273853.png)

**Comment by oOve** [comment]
I'm looking into this now. I found that I had only tested the setup where I had ready made actors, with working prototype tokens.  Now that I enabled them on tokens already on screen, I found some bugs. 
Feel free to join me at [discord](https://discord.gg/5CCAhsKFDp) if you have more questions

**Comment by oOve** [comment]
I found and removed several bugs in the newest release 1.5.3. Could @brunocalado please check if this is still a problem, and if not, close this ticket.

**Comment by brunocalado** [comment]
Worked for a second and stopped.
https://user-images.githubusercontent.com/4999783/161850051-52069f53-3f13-46cf-8d47-8699da423007.mp4

You can use the scene importing it from the compendium. 
![image](https://user-images.githubusercontent.com/4999783/161849933-ed674ec4-22f8-4328-a163-a578bf1a8305.png)

Also, can you add a separator between the options?
![image](https://user-images.githubusercontent.com/4999783/161850141-b45e7642-ebe5-43d1-a56b-cf08fcb16798.png)

**Comment by oOve** [comment]
Could you check if there is any errors in the console (f12)

Would you like a separator between the checkboxes, or between the two different modules?

**Comment by brunocalado** [comment]
### console 
![image](https://user-images.githubusercontent.com/4999783/161987282-4e67e810-e548-430a-9052-fadaffcf0fc5.png)

https://user-images.githubusercontent.com/4999783/161987434-3a8b5e9a-d1ab-48cf-9eab-9d6a7dd49bb6.mp4

### Separator
![image](https://user-images.githubusercontent.com/4999783/161987599-0912b8ff-c44b-4b57-91dd-79282e1d46b1.png)

**Comment by oOve** [comment]
I created the separator, and I agree that it looks better. 
![image](https://user-images.githubusercontent.com/8543541/162329498-c95deb8b-dc8b-4610-a359-b6b8afd340da.png)
The new version out 1.6.1 does have some backwards compatibility issues, but let me know if you have any more issues.

**Comment by brunocalado** [comment]
Working well. Thank you.
